certs_to_trust:
  ca_root_sean: |
    -----BEGIN CERTIFICATE-----
    MIIFVTCCAz2gAwIBAgIRAPfx0lW6r9EjUo6pNhYuW2UwDQYJKoZIhvcNAQELBQAw
    QzELMAkGA1UEBhMCVVMxFTATBgNVBAoTDFNlYW4gTGluZ3JlbjEdMBsGA1UEAxMU
    U2VhbiBMaW5ncmVuIFJvb3QgQ0EwIBcNMTgxMTAzMjEyODQyWhgPMjIxODA5MTYy
    MTI4NDJaMEMxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxTZWFuIExpbmdyZW4xHTAb
    BgNVBAMTFFNlYW4gTGluZ3JlbiBSb290IENBMIICIjANBgkqhkiG9w0BAQEFAAOC
    Ag8AMIICCgKCAgEAvLpCT/eXsF0wFev0rQDFOhSLTbufZxDad/diSr+1Hn+sO+zy
    yImy8Wqj7wkMwCFHccqlmDbaC/3xe8yaB3fRngNX80sk96RJ5FfRR3gN7JnW74ds
    gpm+24L7KkwlQFZ8NFvx1TfF7HqWsMWAmXmn5kJUDjTQ1t4NY7raoDmYFiYQqAZI
    CrV/zxCHOeUHS/273Pvls52K36IYLeYxntz3+BqBO/1BnA6k4Tj068b/wd7FTHg+
    koh9vkzKr8DEqf2dmSM5tujRvzeyD52vTd68+zMy4TrLsHt1FhNo8PJ3N8TLGCI9
    nw+ZjTQccB68CYsfndM4DtKkbtsshJ5tmfL2UqXktetjGp4AYmGZ8Tiklv1lwTaA
    8CFwtcAplxrbxSmZuKRKstI7ttLXek5ntn377XN+si3Lwk9nLtzpeOLpIaDjG6iO
    GqLxiG4WaDgoEg0Kmy4im505IuJwA0C46ghPAxDFtrbRYJHGeVr2Dzpp5uKgfYU6
    BJtImwWJSr+yyqQiNzi/hh3oFAUiDiAJ4XC96MkIeaf/tzhrTSPqYD8NjcqmgFmV
    MUy0YW91u+t8mPgCFWCGXCifxz9rklipWyqsHTNLEUI0kwb8SW6NWTPcxxYlG1sW
    1wiWZv4Zk7M/7f0vrg0FeWTmPUdUKsCL4msGwGGo2eW1PqMIv3Q9EK5GlZECAwEA
    AaNCMEAwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYE
    FL+kYueHn69rFexZcxp2ydJU6KvBMA0GCSqGSIb3DQEBCwUAA4ICAQAzD8uG49cN
    4APqabU9n3zYLVU6ztDeZy8hmFY78autwl/x0fEwdMnoHe8lI3XVMJQyiAjGGgxN
    eraOzY27cEsRvrpbQkwdL+zhB7MKteWit1jZIc6InvVIjw7ZB2fbMziYQWW1hJP3
    NW/mbpWQzBCVX5p0B6IpeIaR5pSR0urxxrzFPAlcqhp3bCT4BZ8s+2Fhzz2YyYT4
    ntlYsYgfpmwQabJiikwJsdiEdU4kzgRv+/xZ0644EakAROP5T+x8jXXrBRpGZXZT
    qV3LCDh8fcmEfX9+3GpdOf7pkzVlzVX02wgV3V+sXJO9xNgNQfXJTqZ9i/dsNqqV
    xI8So3Ox9m0XIUCDc6obQzgYfk3C/9WDbv2u1mKhon0X3URpHtS9mKRjiRsYc8n4
    maNybUwie4ChRlmDhuwOcw4oF7+hl7BTcobvfRZ8yJsMDgESKbbaN0TNopijsSu4
    qac24XBwHSOXRw4jwqdw48wq9YtNztRV3jO+IIF44sw/q3ON7JhmzFsxQTYK6Q2j
    1+5u/dNP9NwQLdu6RhXodfEUK3SlDFonYJFumQzY9ZQue6hB/v95YPAasors62m+
    M8oQK+9DfOT/oC+zdpc6/tdZQejNLfPk71C1ZBuRlqXrlXQjWfaBAP+AtoxptY4h
    JaMt5Sx679s+WYAq5Rf8vh9VM4yk/5w2iA==
    -----END CERTIFICATE-----
  # https://developers.cloudflare.com/gateway/policies/configure-block-page
  cloudflare_block_page: |
    -----BEGIN CERTIFICATE-----
    MIIC6zCCAkygAwIBAgIUI7b68p0pPrCBoW4ptlyvVcPItscwCgYIKoZIzj0EAwQw
    gY0xCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
    YW4gRnJhbmNpc2NvMRgwFgYDVQQKEw9DbG91ZGZsYXJlLCBJbmMxNzA1BgNVBAMT
    LkNsb3VkZmxhcmUgZm9yIFRlYW1zIEVDQyBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkw
    HhcNMjAwMjA0MTYwNTAwWhcNMjUwMjAyMTYwNTAwWjCBjTELMAkGA1UEBhMCVVMx
    EzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBGcmFuY2lzY28xGDAW
    BgNVBAoTD0Nsb3VkZmxhcmUsIEluYzE3MDUGA1UEAxMuQ2xvdWRmbGFyZSBmb3Ig
    VGVhbXMgRUNDIENlcnRpZmljYXRlIEF1dGhvcml0eTCBmzAQBgcqhkjOPQIBBgUr
    gQQAIwOBhgAEAVdXsX8tpA9NAQeEQalvUIcVaFNDvGsR69ysZxOraRWNGHLfq1mi
    P6o3wtmtx/C2OXG01Cw7UFJbKl5MEDxnT2KoAdFSynSJOF2NDoe5LoZHbUW+yR3X
    FDl+MF6JzZ590VLGo6dPBf06UsXbH7PvHH2XKtFt8bBXVNMa5a21RdmpD0Pho0Uw
    QzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBAjAdBgNVHQ4EFgQU
    YBcQng1AEMMNteuRDAMG0/vgFe0wCgYIKoZIzj0EAwQDgYwAMIGIAkIBQU5OTA2h
    YqmFk8paan5ezHVLcmcucsfYw4L/wmeEjCkczRmCVNm6L86LjhWU0v0wER0e+lHO
    3efvjbsu8gIGSagCQgEBnyYMP9gwg8l96QnQ1khFA1ljFlnqc2XgJHDSaAJC0gdz
    +NV3JMeWaD2Rb32jc9r6/a7xY0u0ByqxBQ1OQ0dt7A==
    -----END CERTIFICATE-----
