# run `brew --prefix` to show
brew_prefix: /opt/homebrew

taps:
  - clementtsang/bottom
  - golangci/tap
  - goreleaser/tap
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-versions
  - lingrino/tap

brews:
  - ansible
  - ansible-lint
  - awscli
  - bat
  - clementtsang/bottom/bottom
  - cloudflare-wrangler
  - coreutils
  - ctop
  - delve
  - dive
  - doctl
  - dust
  - exa
  - fd
  - fzf
  - git
  - git-delta
  - git-lfs
  - gh
  - go
  - golangci/tap/golangci-lint
  - goreleaser/tap/goreleaser
  # - hadolint
  - helm
  - hyperfine
  - jq
  - kubernetes-cli
  - less
  - libgit2
  - lingrino/tap/cami
  - lingrino/tap/glen
  - lingrino/tap/vaku
  - markdownlint-cli
  - mas
  - nmap
  - node
  - openssl
  - packer
  - prettyping
  - procs
  - python
  - readline
  - ripgrep
  - rustup-init
  - scc
  - sd
  - serverless
  # - shellcheck
  - shfmt
  - starship
  - terraform
  - tflint
  - vault
  - watch
  - wget
  - yq
  - zoxide
  - zsh

casks:
  - 1password
  - 1password-cli
  - airbuddy
  - alfred
  - aws-vault
  - cardhop
  - cleanshot
  - dash
  - docker
  - fantastical
  - firefox
  - google-chrome
  - gpg-suite
  - hookshot
  - istat-menus
  - iterm2-beta
  - linear-linear
  - logitech-options
  - loom
  - notion
  - slack
  - sublime-text
  - visual-studio-code
  - vlc
  - yubico-yubikey-manager
  - zoom
  - zsa-wally

apps:
  - id: 1487937127
    name: Craft
  - id: 1055511498
    name: Day One
  - id: 1365531024
    name: 1Blocker
  - id: 1547106997
    name: Pins
  - id: 1529448980
    name: Reeder
  - id: 1376402589
    name: StopTheMadness
  - id: 1475387142
    name: Tailscale
  - id: 904280696
    name: Things
